name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 使用している Node.js のバージョンに合わせて変更してください

      # 依存関係のインストール
      - name: Install dependencies
        run: npm install

      # アプリケーションのビルド
      - name: Build
        run: npm run build

      # Google Cloud 認証のセットアップ
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Google Cloud SDK のセットアップ
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: 'latest'

      # プロジェクトIDの設定
      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Docker イメージのビルドとプッシュ
      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloudruntest

      # Cloud Run へのデプロイ
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloudruntest \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloudruntest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated